name: Publish Backend Package

on:
  push:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: darmiel/yadwh-action@v1
        with:
          url: 'http://backend.staging.gyf.d2a.io:9830'
          name: 'BACKEND_STAGED'
          secret: ${{ secrets.STAGED_DEPLOY_SECRET }}
