name: Publish Backend Package

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: darmiel/yadwh-action@v1
        with:
          url: 'https://yadwh.example.com'
          name: 'BACKEND_PROD'
          secret: 'test123'
